### ISSUE TITLE
Valid PDS4 xml input is converted into an invalid json that fails internal datacite validator

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/doi-service#328]
## 🐛 Describe the bug

The error israised from a json labels which is generated internally. The error message does not give a clue where the error is coming from in the input xml file.

## 📜 To Reproduce

**Failure 1**
`pds-doi-cmd release -s loubrieu@jpl.nasa.gov -N eng -i ~/tmp/bundle_edited.xml --force`

[bundle_edited2.xml.zip](https://github.com/NASA-PDS/doi-service/files/8326880/bundle_edited2.xml.zip)

**Failure 2**
[galileo-epd-cal-corrected.zip](https://github.com/NASA-PDS/doi-service/files/8922048/galileo-epd-cal-corrected.zip)
```
$ pds-doi-cmd release -N ppi -s [rsjoyner@jpl.nasa.gov](mailto:rsjoyner@jpl.nasa.gov) -i /home/pds4/input/PPI/Bundles_20220616/ --force --no-review > /home/pds4/result_activate_no_review_PPI_EDP_CAL_20220616.json
INFO pds_doi_service.core.cmd.pds_doi_cmd:main run_dir /home/pds4
INFO pds_doi_service.core.input.input_util:_read_from_path Reading files within directory /home/pds4/input/PPI/Bundles_20220616/
INFO pds_doi_service.core.input.input_util:_read_from_path Reading local file path /home/pds4/input/PPI/Bundles_20220616/bundle_galileo-epd-cal-corrected.xml
INFO pds_doi_service.core.input.input_util:parse_xml_file Parsing xml file bundle_galileo-epd-cal-corrected.xml as a PSD4 label
INFO pds_doi_service.core.input.input_util:_read_from_path Reading local file path /home/pds4/input/PPI/Bundles_20220616/collection-data-cms-events-deltaexe.xml
INFO pds_doi_service.core.input.input_util:parse_xml_file Parsing xml file collection-data-cms-events-deltaexe.xml as a PSD4 label
INFO pds_doi_service.core.input.input_util:_read_from_path Reading local file path /home/pds4/input/PPI/Bundles_20220616/collection-data-cms-events-tof.xml
INFO pds_doi_service.core.input.input_util:parse_xml_file Parsing xml file collection-data-cms-events-tof.xml as a PSD4 label
INFO pds_doi_service.core.input.input_util:_read_from_path Reading local file path /home/pds4/input/PPI/Bundles_20220616/collection-data-epd-channels-high-res.xml
INFO pds_doi_service.core.input.input_util:parse_xml_file Parsing xml file collection-data-epd-channels-high-res.xml as a PSD4 label
INFO pds_doi_service.core.input.input_util:_read_from_path Reading local file path /home/pds4/input/PPI/Bundles_20220616/collection-data-epd-channels-low-res.xml
INFO pds_doi_service.core.input.input_util:parse_xml_file Parsing xml file collection-data-epd-channels-low-res.xml as a PSD4 label
INFO pds_doi_service.core.input.input_util:_read_from_path Reading local file path /home/pds4/input/PPI/Bundles_20220616/collection-data-epd-channels-med-res.xml
INFO pds_doi_service.core.input.input_util:parse_xml_file Parsing xml file collection-data-epd-channels-med-res.xml as a PSD4 label
INFO pds_doi_service.core.db.doi_database:create_connection Connecting to SQLite3 (ver 2.6.0) database /home/pds4/pds-doi-service/doi.db
INFO pds_doi_service.core.db.doi_database:check_if_table_exists Checking for existence of DOI table doi
INFO pds_doi_service.core.db.doi_database:check_if_table_exists Executing query: SELECT count(name) FROM sqlite_master WHERE type='table' AND name='doi'
INFO pds_doi_service.core.outputs.doi_validator:_check_field_site_url Landing page URL https://pds.nasa.gov/ds-view/pds/viewBundle.jsp?identifier=urn%3Anasa%3Apds%3Agalileo-epd-cal-corrected&;version=1.0 is reachable
Traceback (most recent call last):
  File "/home/pds4/pds-doi-service/lib/python3.9/site-packages/pds_doi_service/core/actions/release.py", line 274, in run
    dois = self._validate_dois(dois)
  File "/home/pds4/pds-doi-service/lib/python3.9/site-packages/pds_doi_service/core/actions/release.py", line 214, in _validate_dois
    self._validator_service.validate(single_doi_label)
  File "/home/pds4/pds-doi-service/lib/python3.9/site-packages/pds_doi_service/core/outputs/datacite/datacite_validator.py", line 73, in validate
    json_contents = json.loads(label_contents)
  File "/usr/local/python-3.9.5/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/python-3.9.5/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/python-3.9.5/lib/python3.9/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 142 column 578 (char 6545)
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
  File "/home/pds4/pds-doi-service/bin/pds-doi-cmd", line 8, in <module>
    sys.exit(main())
  File "/home/pds4/pds-doi-service/lib/python3.9/site-packages/pds_doi_service/core/cmd/pds_doi_cmd.py", line 42, in main
    output = action.run(**kwargs)
  File "/home/pds4/pds-doi-service/lib/python3.9/site-packages/pds_doi_service/core/actions/release.py", line 322, in run
    raise CriticalDOIException(str(err))
pds_doi_service.core.entities.exceptions.CriticalDOIException: Expecting ',' delimiter: line 142 column 578 (char 6545)
```

## 🕵️ Expected behavior

We would like to catch the error when the json file is generated and not when it is parsed.

We might need to sanitize (remove or encode " for example) the strings which are written in the json file before it is sent.

## 📚 Version of Software Used

v2.2.0

## 🩺 Test Data / Additional context

See above

---

## 🦄 Related requirements
🦄 https://github.com/NASA-PDS/doi-service/issues/7

**Comment by tloubrieu-jpl** [comment]
@rsjoyner this is the bug that I created to track what we said today. Thanks

**Comment by tloubrieu-jpl** [comment]
The solution for now will be to escape the quotation.

@nutjob4life will also create another ticket for a longer term solution where we build the json directly in python rather than using a template.

**Comment by nutjob4life** [comment]
Fix in [pull request](https://github.com/NASA-PDS/doi-service/issues/328). Long term [issue filed](https://github.com/NASA-PDS/doi-service/issues/340).

**Comment by rsjoyner** [comment]
From one of the comments herein, I was able to discern the "edits" that were needed to "force" the s/w to mint the DOIs.

I will point out that had the diagnostics been a bit (or a lot) more informative / useful, I would have hand edited the files long ago and moved on....

**Comment by gxtchen** [comment]
@tloubrieu-jpl @viviant100 I am still seeing the InputFormatException for the [bundle_edited2.xml](https://github.com/NASA-PDS/doi-service/files/8326880/bundle_edited2.xml.zip) file after generating the Json file.
[test1.log](https://github.com/NASA-PDS/doi-service/files/9089710/test1.log)

**Comment by tloubrieu-jpl** [comment]
@gxtchen , the fix is available in an unstable version of the package, you should deploy it with this command:

    pip install https://github.com/NASA-PDS/doi-service/releases/download/v2.2.1-dev/pds_doi_service-2.2.1.dev0-py3-none-any.whl

Is that what you used ?

Thanks

**Comment by gxtchen** [comment]
@tloubrieu-jpl @nutjob4life Thanks, it works now. The error was cause by using a older version of python 3.9

**Comment by tloubrieu-jpl** [comment]
Perfect thanks @gxtchen
